[Partition]
Type=usr
Format=btrfs
SizeMinBytes=8G
SizeMaxBytes=16G
Subvolumes=/var
Subvolumes=/home
Subvolumes=/snapshots
Verity=data
VerityMatchKey=usr
MakeDirectories=/var/lib/roch
MakeDirectories=/var/lib/roch/profiles
MakeDirectories=/var/lib/roch/snapshots
MakeDirectories=/ui
