[Partition]
Type=usr
Format=btrfs
SizeMinBytes=12G
SizeMaxBytes=20G
Subvolumes=/home
Subvolumes=/var
Subvolumes=/snapshots
Subvolumes=/ui
Verity=data
VerityMatchKey=usr
MakeDirectories=/home
MakeDirectories=/var
MakeDirectories=/snapshots
MakeDirectories=/ui
MakeDirectories=/var/lib/roch
MakeDirectories=/var/lib/roch/profiles
MakeDirectories=/var/lib/roch/snapshots
