# Roch OS mkinitcpio configuration
# Optimized for btrfs, systemd, and UKI

MODULES=(btrfs)
BINARIES=()
FILES=()
HOOKS=(base systemd autodetect microcode modconf kms keyboard sd-vconsole block filesystems fsck)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)
